ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr
AVR_TOOLS_DIR = /usr
ARDUINO_LIBS = Ethernet Ethernet/utility SPI
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0*

include /usr/share/arduino/Arduino.mk
